#GoogleCameraMod
include $(CLEAR_VARS)
LOCAL_MODULE := GoogleCameraMod 
LOCAL_SRC_FILES := GoogleCameraMod/$(LOCAL_MODULE).apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_OVERRIDES_PACKAGES := Camera2 Snap
include $(BUILD_PREBUILT)
